### ISSUE TITLE
SPI instead of i2c

### ISSUE THREAD

**Issue by maxholgasson** [embeddedadventures/MOD-1016#1]
Hi,

is there also an example for using spi?

**Comment by dr4nc3s** [comment]
Hi Max, 

Thanks for reminding me. This has been on my to-do list, but other tasks kept me busy. SPI support in the library has been added. Let me know if it works for you and if you discover any issues.

Thanks!

**Comment by maxholgasson** [comment]
Hi,

thanks!  I got many errors like

MOD1016_demo:94: error: variable or field 'translateIRQ' declared void
  void translateIRQ(uns8 irq) {
                    ^
MOD1016_demo:94: error: 'uns8' was not declared in this scope
MOD1016_demo:59: error: 'SPI' was not declared in this scope
    SPI.begin();
    ^
MOD1016_demo:60: error: 'mod1016' was not declared in this scope
    mod1016.init(IRQ_PIN, CS_PIN);
    ^
MOD1016_demo:78: error: 'IRQ_pin' was not declared in this scope
    pinMode(IRQ_pin, INPUT);
            ^
MOD1016_demo:85: error: 'mod1016' was not declared in this scope
      translateIRQ(mod1016.getIRQ());
                   ^
MOD1016_demo:85: error: 'translateIRQ' was not declared in this scope
      translateIRQ(mod1016.getIRQ());
                                   ^

Am 17.10.16 um 21:26 schrieb dr4nc3s:

> Hi Max,
> 
> Thanks for reminding me. This has been on my to-do list, but other tasks kept me busy. SPI support in the library has been added. Let me know if it works for you and if you discover any issues.
> 
> Thanks!

**Comment by dr4nc3s** [comment]
Demo sketch was inconsistent with my version. Sorry about that. Check it now
