### ISSUE TITLE
No constant usage of well defined integers

### ISSUE THREAD

**Issue by Rotzbua** [embeddedadventures/MOD-1016#3]
Hi,

this library do not always use well defined integers.
For example the `irq` is a unsigned 8 bit integer `uns8`, but the function accepts `int` which could be any size.
I think the library should be refactored and use always well defined integers like `uns8`.

Some bad functions:
```c++
void autoTuneCaps(int irq);
sgn32 getFrequency(int irq);
void freqPerTuneCaps(int fdiv, int irq);
void auto_calibrate(int irq);

class AS3935Class
{
private:
	uns8	_irq; // here well defined
public:
	void init(int IRQ_pin); // bad
	int  calculateDistance();
	int  getDivisionRatio();
	unsigned int  getIntensity();
};
```

**Comment by dr4nc3s** [comment]
Thanks for pointing that out! I'll get to work on it and update it after testing :)
