### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by szerwi** [embeddedadventures/MOD-1016#4]
Hi,

I'm trying to upload a code to ESP32 (I've tried Arduino Uno also) but while compiling I have an error: 

C:\Program Files (x86)\Arduino\libraries\MOD-1016-master\AS3935.cpp: In member function 'void AS3935Class::init(uint8_t)':

C:\Program Files (x86)\Arduino\libraries\MOD-1016-master\AS3935.cpp:116:10: error: 'IRQ_pin' was not declared in this scope

  pinMode(IRQ_pin, INPUT);

          ^

exit status 1

I've tried to replace IRQ_PIN with IRQ_pin in code, but the error is the same. I'm using Arduino IDE 1.8.1

**Comment by dr4nc3s** [comment]
Thank you very much for pointing that out. It was an overlooked mistake that I didn't verify.  The error has been fixed and it should be fine now. 
Parameter "irqPin" and used name "IRQ_pin" were inconsistent.
