### ISSUE TITLE
ino file doesn't work create.auduino.cc

### ISSUE THREAD

**Issue by kevkearney** [embeddedadventures/MOD-1016#5]
I can get the project to compile in the Arduino thick app, but their cloud IDE seems to have a couple of issues.
The first one is that the AS3935.h library conflicts with one of the same name in their core libraries. 
I changed the name just to see if it works, and I ran into some other errors. Note: I renamed the library AS3935mod.cpp to avoid the conflict.

`/tmp/792930693/custom/MOD-1016-master/AS3935mod.cpp:41:10: error: 'sgn32' does not name a type
volatile sgn32 pulse = 0;
^
/tmp/792930693/custom/MOD-1016-master/AS3935mod.cpp:42:1: error: 'sgn32' does not name a type
sgn32 cap_frequencies[16];
^
/tmp/792930693/custom/MOD-1016-master/AS3935mod.cpp: In function 'void pulseDetected()':
/tmp/792930693/custom/MOD-1016-master/AS3935mod.cpp:46:3: error: 'pulse' was not declared in this scope
pulse++;
^
/tmp/792930693/custom/MOD-1016-master/AS3935mod.cpp: At global scope:
/tmp/792930693/custom/MOD-1016-master/AS3935mod.cpp:49:19: error: variable or field 'autoTuneCaps' declared void
void autoTuneCaps(uns8 irq) {
^
/tmp/792930693/custom/MOD-1016-master/AS3935mod.cpp:49:19: error: 'uns8' was not declared in this scope
/tmp/792930693/custom/MOD-1016-master/AS3935mod.cpp:58:1: error: 'sgn32' does not name a type
sgn32 getFrequency(uns8 irq) {
^
/tmp/792930693/custom/MOD-1016-master/AS3935mod.cpp:70:22: error: variable or field 'freqPerTuneCaps' declared void
void freqPerTuneCaps(uns16 fdiv, uns8 irq) {
^
/tmp/792930693/custom/MOD-1016-master/AS3935mod.cpp:70:22: error: 'uns16' was not declared in this scope
/tmp/792930693/custom/MOD-1016-master/AS3935mod.cpp:70:34: error: 'uns8' was not declared in this scope
void freqPerTuneCaps(uns16 fdiv, uns8 irq) {
^
exit status 1`

**Comment by dr4nc3s** [comment]
Was the header file also renamed to AS3935mod.h?

**Comment by kevkearney** [comment]
Yes it was.

You can check out the sketch here:
https://create.arduino.cc/editor/kevkearney/e0a4a696-eb44-4291-b22c-f7dcc7552cbc/preview

**Comment by dr4nc3s** [comment]
I just tried it and made the same modifications: renamed the header and cpp files to "AS3935mod" and modified 
`#ifndef __AS3935_h
#define __AS3935_h`
to
`#ifndef__AS3935mod_h
#define __AS3935mod_h`

Made the same modification in the #include line in the .cpp file. It works fine for me. Can you show me the library file modifications you made?

**Comment by kevkearney** [comment]
Yup, you are right. I missed a change.
It works now. Do you know of any way to change the name to not conflict with the other AS3935 library? Or should this remain a manual change.

**Comment by dr4nc3s** [comment]
I think it'd be better to keep it as a manual change.
