### ISSUE TITLE
Can't detect lightning

### ISSUE THREAD

**Issue by szerwi** [embeddedadventures/MOD-1016#6]
Hi,

There is a storm near to me (about 20km) and I'm checking the MOD-1016 lightning detector. Most of the lightnings that are 20km far away are counting as "DISTURBER". When some lightnings are detected properly, the distance is calculated wrongly (about 15km difference). Is there any way to calibrate sensor? I've set Tune 2, like my box with sensor say and I'm trying different noise floor settings. The sensor is near the window, I've set it to InDoors settings. When I set Outdoors and go with the sensor outdoors, it was detecting nothing.

**Comment by dr4nc3s** [comment]
You can try two things to try and improve the sensors' sensitivity. First is to call the autoTuneCaps() function that's part of the library. This runs through all the values and tunes the sensor to the best value possible. Another thing you can do is manually set the tuning yourself and monitor the measurements you get until you find one that works better for you. 

Here's also a short list of things that affected my values while testing the sensor library:

- breadboarding
- proximity to other electronics or high frequency devices
- basement vs. above ground location

Let us know how it goes

**Comment by szerwi** [comment]
Should I also change Nosiefloor or it doesn't change anything? If I place the sensor on the roof of my house, it should be better than placing it in the house, near the window? If I place it near the window I should set Indoors, and if I set it on the roof I should set Outdoors?

**Comment by szerwi** [comment]
It's now detecting disturber all the time. I don't know why...

**Comment by kevkearney** [comment]
As for the distance problem: If you read the datasheet for the as3935. It states that the distance provided is not necessarily the distance of the lightning strike, but is the estimated distance of the storm front.
It uses a formula that counts how many strikes happen in a certain time period to calculate how close the storm is to your location.

>  The estimated distance which is displayed in the distance estimation register does not represent the distance
to the single lightning but the estimated distance to the leading edge of the storm.

**Comment by szerwi** [comment]
I've returned to old settings: Tune 2 Noisefloor 5. I've changed only location of the sensor a little bit and it's sending DISTURBER DETECTED all the time... :/

**Comment by szerwi** [comment]
Should the sensor detect lightning every single strike or strike can be detected as disturber and the sensor will only show lightning from time to time?

**Comment by kevkearney** [comment]
You might have some RFI nearby. Does it continuously show disturber, even though there is no storm nearby?

**Comment by dr4nc3s** [comment]
A disturber notif all the time could be due to other interference (I've learned from hours of wondering why it won't detect lightning). Are there any other electronic equipment nearby?

**Comment by szerwi** [comment]
Yes, there is a computer. It shows disturber from time to time where there is no lightning, but now it shows disturber very often, and almost every of them are lightnings.

**Comment by szerwi** [comment]
There was a strike near my house (0,5km) and sensor also shown disturber

**Comment by dr4nc3s** [comment]
Did the autotune function give you a 2 for the tuning value?

**Comment by szerwi** [comment]
Yes

**Comment by dr4nc3s** [comment]
Try a 3 or 4 and see how it goes. If the lightning is still being detected strictly as disturbers and the sensor only detects those now (no other noise in the background) then it's most likely an issue with the tuning.

**Comment by dr4nc3s** [comment]
Try disabling disturbers as well and see if it works

**Comment by szerwi** [comment]
How to disable disturbers?

**Comment by szerwi** [comment]
On tune 3 and 4 is the same. I saw that some strikes are shown 2 times as a disturber

**Comment by dr4nc3s** [comment]
disableDisturbers() to disable them. 
Good, so a different tuning value works a little better. Try disabling the disturbers

**Comment by szerwi** [comment]
No, different tuning didn't work better. Worked the same as tune 2.

**Comment by dr4nc3s** [comment]
What was the change that you made for the lightning to be detected?

**Comment by szerwi** [comment]
I think nothing, lightning detection is shown only sometimes.

**Comment by szerwi** [comment]
I disabled disturbers. Only one lightning detected 5km away, but there was at least 10 of them

**Comment by dr4nc3s** [comment]
Ok. I'm not sure how else to remedy that. Last attempt would be to, if you have one, hook up your current set up to an LCD display and have results go out to that. I want to keep the set up away from the computer. Hopefully that helps out a bit more.

**Comment by szerwi** [comment]
Storm has gone away... :) I will try it later, but I don't think it's a solution :/ Arduino can also produce some noises

**Comment by szerwi** [comment]
There is some strikers. It is about 20km away, the sensor said 10km away... :/

**Comment by szerwi** [comment]
How the options indoors and outdoors are working?

**Comment by szerwi** [comment]
I've connected the LCD. On indoors settings it didn't catch anything when strike was 15km away. On outdoors settings it's catching some disturbers all the time...

**Comment by szerwi** [comment]
So, there was a big storm today in my area and my sensor was working, but not fantastic. I had a LCD screen connected to Arduino, and sensor was only detecting lightnings as "DISTURBER". I'd disconnected LCD screen and sensor started to detect some LIGHTNING and showed distance. But not every lightning was detected as "LIGHTNING", but as "DISTURBER". Maybe there were also some noise from Arduino. Next time I will try to move the sensor away from Arduino. Also the sensor was in home now, maybe if I had placed it outside, it would have been better. Is it normal in your opinion? :D
